# Makefile for matvec homework
# @author Fuat Keceli
# @revision $Id$
# @ID $Id: Makefile 8306 2009-04-28 15:34:45Z keceli $
#
#===========================================================================
#
# STUDENTID= your account name.
#

include /opt/xmt/class/make/matvec.mk
